# Generated by Django 4.0.3 on 2022-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='main_registration_title_length',
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gte', 2)), name='main_registration_name_length'),
        ),
    ]
