# Generated by Django 4.0.3 on 2022-04-21 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_registration_main_registration_name_length_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='main_registration_name_length',
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
