# Generated by Django 4.0.3 on 2022-04-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_registration_name_alter_registration_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='telnumber',
            new_name='phonenumber',
        ),
    ]
