# Generated by Django 4.0.3 on 2022-04-22 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_telnumber_registration_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='phonenumber',
            new_name='telnumber',
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
