# Generated by Django 4.0.3 on 2022-04-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_registration_telnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postes',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='name',
        ),
    ]
